import obsidianmd from 'eslint-plugin-obsidianmd';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'main.js',
      'node_modules/**',
      // Worktrees checked out inside the repo hold a second copy of the source
      // that is not covered by this project's tsconfig, which makes the
      // type-aware rules fail to load.
      '.claude/**',
      '.obsidian-cache/**',
      'test/screenshots/**',
      // Generated by `npm run icons`.
      'src/iconAliases.ts',
    ],
  },
  ...tseslint.configs.recommended,
  ...obsidianmd.configs.recommended,
  {
    // obsidianmd's recommended set includes type-aware rules, which only work
    // for files covered by tsconfig.json.
    files: ['src/**/*.ts', 'test/**/*.ts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // Build scripts and the wdio config live outside tsconfig's include.
    files: ['**/*.mjs', '**/*.mts'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // TypeScript already resolves globals; core no-undef doesn't know about
    // Obsidian's DOM helpers (createDiv, activeWindow, ...) or ambient types.
    files: ['**/*.ts', '**/*.mts'],
    rules: { 'no-undef': 'off' },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    // e2e tests reach into Obsidian internals that aren't in the public
    // typings -- app.plugins, app.setting -- so the values genuinely are `any`.
    files: ['test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      // Test helpers run in the Node-side wdio runner, not inside Obsidian,
      // so the mobile-compatibility ban on Node builtins doesn't apply.
      'import/no-nodejs-modules': 'off',
      // The screenshot capture deliberately restyles the editor to frame the
      // image. That is not shipped plugin code, so the theming rule that
      // pushes style changes into CSS classes does not apply.
      'obsidianmd/no-static-styles-assignment': 'off',
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-prototype-builtins': 'off',
    },
  }
);
